export { Home } from "./Home";
export { Reports } from "./Reports";
export { Projects } from "./Projects";
export { Dashboard } from "./Dashboard";
export { Login } from "./Login";
export { Register } from "./Register";
export { SubmitReport } from "./SubmitReport";
export { ReportIncident } from "./ReportIncident";
export { ReportVerified } from "./ReportVerified";
